/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author chris
 */
public class AsistenciaEstudiantes extends javax.swing.JFrame {

    /**
     * Creates new form RegistroAsistencia
     */
    public AsistenciaEstudiantes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMenuAsistencia = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_estudiantes = new javax.swing.JTable();
        txtBuscarEstudiantes = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbTurno = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnMarcarTardanza = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerFecha = new javax.swing.JSpinner();
        cmbCarrera = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbCiclo = new javax.swing.JComboBox<>();
        btnMarcarAsistencia = new javax.swing.JButton();
        btnMarcarFalta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(181, 181, 181));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("ASISTENCIA DE ESTUDIANTES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 690, 80));

        btnMenuAsistencia.setBackground(new java.awt.Color(181, 181, 181));
        btnMenuAsistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_menu_80.png"))); // NOI18N
        btnMenuAsistencia.setBorder(null);
        btnMenuAsistencia.setOpaque(true);
        btnMenuAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuAsistenciaActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenuAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 80, 80));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_iestpvillamaria_80.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 100));

        table_estudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombres", "Apellidos", "Carrera", "Ciclo", "Turno", "Estado"
            }
        ));
        jScrollPane1.setViewportView(table_estudiantes);
        if (table_estudiantes.getColumnModel().getColumnCount() > 0) {
            table_estudiantes.getColumnModel().getColumn(0).setResizable(false);
            table_estudiantes.getColumnModel().getColumn(1).setResizable(false);
            table_estudiantes.getColumnModel().getColumn(2).setResizable(false);
            table_estudiantes.getColumnModel().getColumn(3).setResizable(false);
            table_estudiantes.getColumnModel().getColumn(4).setResizable(false);
            table_estudiantes.getColumnModel().getColumn(5).setResizable(false);
            table_estudiantes.getColumnModel().getColumn(6).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 950, 400));
        getContentPane().add(txtBuscarEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 300, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Buscar:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 70, 30));

        cmbTurno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTurnoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 130, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Turno:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        btnMarcarTardanza.setBackground(new java.awt.Color(255, 204, 51));
        btnMarcarTardanza.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMarcarTardanza.setForeground(new java.awt.Color(255, 255, 255));
        btnMarcarTardanza.setText("Marcar Tardanza");
        btnMarcarTardanza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcarTardanzaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMarcarTardanza, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, 160, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Fecha:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 70, 30));

        jSpinnerFecha.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_WEEK));
        getContentPane().add(jSpinnerFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, -1, 30));

        cmbCarrera.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCarreraActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 130, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Carrera:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Ciclo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        cmbCiclo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbCiclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCicloActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCiclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 130, 30));

        btnMarcarAsistencia.setBackground(new java.awt.Color(51, 204, 0));
        btnMarcarAsistencia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMarcarAsistencia.setForeground(new java.awt.Color(255, 255, 255));
        btnMarcarAsistencia.setText("Marcar Asistencia");
        btnMarcarAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcarAsistenciaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMarcarAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 110, 160, 40));

        btnMarcarFalta.setBackground(new java.awt.Color(255, 51, 51));
        btnMarcarFalta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMarcarFalta.setForeground(new java.awt.Color(255, 255, 255));
        btnMarcarFalta.setText("Marcar Falta");
        btnMarcarFalta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcarFaltaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMarcarFalta, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 210, 160, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuAsistenciaActionPerformed
        VistaMenuPrincipal menu = new VistaMenuPrincipal();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_btnMenuAsistenciaActionPerformed

    private void cmbTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTurnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTurnoActionPerformed

    private void btnMarcarTardanzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarTardanzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMarcarTardanzaActionPerformed

    private void cmbCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCarreraActionPerformed

    private void cmbCicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCicloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCicloActionPerformed

    private void btnMarcarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarAsistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMarcarAsistenciaActionPerformed

    private void btnMarcarFaltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarFaltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMarcarFaltaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIbtnMarcarTardanzaInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsistenciaEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsistenciaEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsistenciaEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsistenciaEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsistenciaEstudiantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMarcarAsistencia;
    private javax.swing.JButton btnMarcarFalta;
    private javax.swing.JButton btnMarcarTardanza;
    private javax.swing.JButton btnMenuAsistencia;
    private javax.swing.JComboBox<String> cmbCarrera;
    private javax.swing.JComboBox<String> cmbCiclo;
    private javax.swing.JComboBox<String> cmbTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerFecha;
    private javax.swing.JTable table_estudiantes;
    private javax.swing.JTextField txtBuscarEstudiantes;
    // End of variables declaration//GEN-END:variables
}
